name: Unit Test

on:
  workflow_call:
    inputs:
      go-version:
        default: "1.18"
        required: false
        type: string
    secrets:
      KEEPASSNOTIFIER_BOT_PAT:
        required: true
jobs:
  tests:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.KEEPASSNOTIFIER_BOT_PAT }}
        run: make install && make test_unit_codecov